### ISSUE TITLE
[MAUI] Update the bindings to work in .net 6+ (Maui)

### ISSUE THREAD

**Issue by AdamDiament** [VisualService/dotnet-zoom-meeting-SDK#11]
This might need to be a separate repo, as upgrading the target framework to add maui support will break Xamarin forms. I haven't decided what is best yet. Thoughts welcome, in particular PRs or ways to get XF-Maui side-by-side working.

Possible useful resources

https://learn.microsoft.com/en-us/events/dotnetconf-focus-on-maui/binding-native-libraries-for-dotnet-maui

**Comment by AdamDiament** [comment]
The first step will be to make sure all the referenced nuget dependencies support .net6 android/ios

I've had an initial audit, most do thankfully. There are two that don't:

1)  Xamarin.Google.Android.Material 1.3.1. Upgrading to 1.6.1 should provide a version that compiles for .net 6
2) Com.Airbnb.Xamarin.Forms.Lottie 4.1.0 - there is[ an issue on the lottie repo requesting .net 6 support here](https://github.com/Baseflow/LottieXamarin/issues/386) if you want to bump it that would be helpful

**Comment by mdima** [comment]
Hi Adam,
   I passed through this already for another project. You should set the Build Action to "AndroidLibrary" for the .aar files. 

Have a good day,
Michele

**Comment by AdamDiament** [comment]
Hey @mdima, nice to hear from you! Thanks for the tip. I've renamed the repo now to a more generic dotnet name, and started the process of adding MAUI support in a separate sln. 

For android, I have the aar loading now I've set it to the correct build configuration. I am working through some weird missing resource build failures. Have not started iOS yet. If you had any time to jump in and help with either, we'd love the support!

**Comment by AdamDiament** [comment]
Trying to build the android, and getting this:

![image](https://github.com/VisualService/dotnet-zoom-meeting-SDK/assets/6513834/56ea459f-cc72-402b-8be4-f55b1c357402)

I think the real errors are the missing resources. I remember dealing with similar issues during the Xamarin days. Not sure of the solution for MAUI.

**Comment by AdamDiament** [comment]
Captain's log: star-date 24th July, Tellus 

I added the nuget packages to match the xamarin version, and still get the same missing resource errors. As of right now, stuck!

**Comment by AdamDiament** [comment]
C.C @icalderond if you have any insight

**Comment by AdamDiament** [comment]
The missing resources are all defined in ZoomCommonLib. I'm wondering if there is an issue with how maui handles one binding library that references another. (HeadProject => MobileRTC => ZoomCommonLib)

**Comment by samirgcofficial** [comment]
Any updates for the fixes ?

**Comment by AdamDiament** [comment]
No, I am still working through the issues as described in the comments

**Comment by AdamDiament** [comment]
An update, although without good news, is that on the MAUI branch I used the full fat exoplayer, and a version of lottie that compiled for .net 7. Yet I still get the errors, so either one of those packages is causing problems, or another package is the problem, or there is a deeper problem with MAUI bindings that I don't understand. If anyone has any wisdom to share, I am all ears!

**Comment by AdamDiament** [comment]
After much much much trial and error and a big dose of help from @timjamwoo I got a zoom call working on MAUI Android! Stay tuned for a PR and a nuget package. 

iOS support will come soon too hopefully.

**Comment by AdamDiament** [comment]
@timjamwoo when doing this for iOS, you have two options. 1) copying the current project from XF over into the mau sln and porting the csproj file and 2) creating a new project from scratch. If you do two, the top one in the screenshot is the project type you need

![image](https://github.com/VisualService/dotnet-zoom-meeting-SDK/assets/6513834/9468b6b9-d60c-4e5f-bd3f-a26ea3a94e01)

Here are some instructions for the porting option, which will also be useful if you start from scratch as it contains details of breaking changes between xf and iOS you'd have to deal with either way.

https://github.com/dotnet/docs-maui/issues/1514

For Android I used the new project template, but I'm sure either would work fine.

**Comment by AdamDiament** [comment]
@timjamwoo 

Required iOS tasks

- [ ] Port or create new project inside the MAUI sln
- [ ] Update the sample app to target iOS too (change targeted projects in csproj file, add platforms folder with relevant appdelegate.cs files etc)
- [ ] Implement any needed platform specific iOS zoom services in the sample app
- [ ] Confirm you can launch a zoom call in default ui on the sample app
- [ ] Create a nuget package from the iOS lib and test it via a local nuget feed in the MAUI branch of iOS on Visual Service main project (We might need to reimplement the non mock zoom .sln for MAUI before doing this part)

**Comment by AdamDiament** [comment]
@AdamDiament remaining Android Tasks

- [ ] Build the nuget package for Android
- [ ] Test it locally via local nuget feed in the main visual service MAUI sln  (We might need to reimplement the non mock zoom .sln for MAUI before doing this part)
- [ ] Upload it to nuget.org
- [ ] Link to the online version
