### ISSUE TITLE
[XF] Does this support MobileRTCScreenShare?

### ISSUE THREAD

**Issue by jh-mobitech** [VisualService/dotnet-zoom-meeting-SDK#17]
Does this support MobileRTCScreenShare? If not, can you please support that?

**Comment by AdamDiament** [comment]
@jh-mobitech Currently I believe not, although the original repository that this one was based on used to, so there is no reason in theory that it couldn't. I would welcome a PR!

**Comment by AdamDiament** [comment]
@AdamDiament

**Comment by AdamDiament** [comment]
I'm closing this as the question has been answered. If someone wants to add a PR for MobileScreenShare then I am open for that, but I have no plans to implement it myself.
