### ISSUE TITLE
Ios & macos

### ISSUE THREAD

**Issue by NileshPhalke123** [VisualService/dotnet-zoom-meeting-SDK#22]
Eagerly waiting for the zoom ios & macos binding libraries.

**Comment by icalderond** [comment]
This support is not yet implemented and this is described in the README.md. If you want help to add support for that then send a new PR.

Menawhile this issue have to be closed @AdamDiament given that this part is being development.

**Comment by AdamDiament** [comment]
Hi @NileshPhalke123 thanks for your interest. iOS is already supported for Xamarin Forms with the caveat that the nuget isn't available currently, but you can integrate the codebase directly. Nuget support for iOS will hopefully be available soon. MacOS is not in the pipeline, but if community members want it, then I would accept a PR. MAui for iOS and Android is a work in progress, with some blocking issues in #11
