### ISSUE TITLE
Maui App crash while joining the meeting.

### ISSUE THREAD

**Issue by NileshPhalke123** [VisualService/dotnet-zoom-meeting-SDK#37]
Device - iPhone XR (iOS version 16.6.1)
Visual Studio for Mac 17.6 (build 1575)
I've provided the screenshot. Please help!
![Screenshot 2023-10-09 at 1 25 46 PM](https://github.com/VisualService/dotnet-zoom-meeting-SDK/assets/120553107/23d8346d-3015-46cd-a32a-bea46971feaa)

**Comment by AdamDiament** [comment]
@NileshPhalke123 

If you are not already, make sure that anywhere you access the zoomsdk object you do it on the main thread.

If you are already doing that, or you change your code to do it and still get the error,

Do you have a stack trace from visual studio with some maui level errors? 

Can you post a snippet of code around how you are joining the meeting?

**Comment by NileshPhalke123** [comment]
@AdamDiament 
Thank you for your quick response. I have already added the screenshot of the error. Sdk is initializing properly and I'm getting state as Connecting  and Waiting progress icon is visible but after that app crashes immediately. Please check the files attached below. I've also added the permissions in the info.plist file as given in the sample app.  same error again & again.
![Screenshot 2023-10-11 at 10 51 51 AM](https://github.com/VisualService/dotnet-zoom-meeting-SDK/assets/120553107/02072b1b-0937-4453-bf39-81116e9afa92)
![Screenshot 2023-10-11 at 10 57 52 AM](https://github.com/VisualService/dotnet-zoom-meeting-SDK/assets/120553107/fcc09bb6-d47d-414b-8535-fcfee454c674)
![Screenshot 2023-10-11 at 10 57 32 AM](https://github.com/VisualService/dotnet-zoom-meeting-SDK/assets/120553107/9148d5af-562f-4717-8f5c-7110a96285d3)
![Screenshot 2023-10-11 at 10 56 53 AM](https://github.com/VisualService/dotnet-zoom-meeting-SDK/assets/120553107/55833446-2b15-441d-9770-78715d4bfd7b)
![Screenshot 2023-10-11 at 10 53 57 AM](https://github.com/VisualService/dotnet-zoom-meeting-SDK/assets/120553107/2003acac-3654-495b-9f61-484b8dd694b4)
![Screenshot 2023-10-11 at 10 53 18 AM](https://github.com/VisualService/dotnet-zoom-meeting-SDK/assets/120553107/9f0b2191-8b92-402f-a1d1-02b45a467060)
![Screenshot 2023-10-11 at 10 52 52 AM](https://github.com/VisualService/dotnet-zoom-meeting-SDK/assets/120553107/1f40e565-70a4-4353-ade6-02dd35e43c92)

**Comment by AdamDiament** [comment]
Thanks @NileshPhalke123 

Can you upload a zipped .sln to see if we can reproduce the bug here

@timjamwoo Once we have the code can you have a look at this when you're back please?

**Comment by NileshPhalke123** [comment]
@Adam Diament
Please check the zip. I 'm using nuget package provided by the link:
https://www.nuget.org/packages/ZoomMeetingSDK.DotNet.iOS/5.15.7.9685

**Comment by NileshPhalke123** [comment]
Hey guys, any updates? Have you made any breakthroughs?
I'm eagerly waiting for the solution.

**Comment by timjamwoo** [comment]
> Hey guys, any updates? Have you made any breakthroughs? I'm eagerly waiting for the solution.

Hi Nilesh, I can't see the zip you mentioned. Can you attach it to this issue and I'll try to take a look?

**Comment by NileshPhalke123** [comment]
@timjamwoo Sorry for the inconvenience. I already mailed it to @AdamDiament . I'm sending it again. Please check it. Sorry for the late reply.
[ZoomTest.zip](https://github.com/VisualService/dotnet-zoom-meeting-SDK/files/13074318/ZoomTest.zip)

**Comment by NileshPhalke123** [comment]
Hi timjamwoo, have you checked the project?  is it working on your side?

**Comment by timjamwoo** [comment]
> Hi timjamwoo, have you checked the project? is it working on your side?

Hi @NileshPhalke123, I figured out your problem. Check your info.plist file - the last 3 keys have been corrupted somehow. If you set it as follows, it works fine:
```
	<key>NSCameraUsageDescription</key>
	<string>New Entry</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>New Entry</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>New Entry</string>
```

**Comment by NileshPhalke123** [comment]
@timjamwoo Thank you man,you saved my life. How did you figured out that problem ?
I have one more question . Can we use appkey and secret instead of jwt to initialize the sdk?

**Comment by timjamwoo** [comment]
> @timjamwoo Thank you man,you saved my life. How did you figured out that problem ? 

I googled "_ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode" and found [this SO question](https://stackoverflow.com/questions/75790787/crash-when-moving-xamarin-ios-binding-library-to-net-6). The answer at the bottom pointed me to your info.plist.

> I have one more question . Can we use appkey and secret instead of jwt to initialize the sdk?

I'm afraid not - Zoom have removed this ability as of version 5.15.
