### ISSUE TITLE
Xamarin Android Zoom SDK not working

### ISSUE THREAD

**Issue by fayazvar** [VisualService/dotnet-zoom-meeting-SDK#39]
public async Task<bool> InitZoomLib(string token)
 {
     zoomSDK = ZoomSDK.Instance;
     var zoomInitParams = new ZoomSDKInitParams
     {
         JwtToken = token
     };
     zoomSDK.Initialize(Android.App.Application.Context, this, zoomInitParams);
     await Task.Delay(5000);

     return true;
 }

This code does not work, It is not Initializing the ZoomSDK, it throws some error.

**Comment by AdamDiament** [comment]
I can't do much with this

More information please

* Device, version, exact error from logs etc

**Comment by AdamDiament** [comment]
I am closing this as it relates to Xamarin, which we no longer support. If you have an issue with the MAUI nuget package, please file another issue. Please include logs and detailed replication steps too.
