### ISSUE TITLE
Compile issue with latest version.

### ISSUE THREAD

**Issue by logikonline** [VisualService/dotnet-zoom-meeting-SDK#47]
It hangs on a library when I try to compile the 6.1.1.22761 into my project.  It appears there is a conflict that Visual Studio and Rider cannot resolve.

Therefore, I must revert to 5.17.0.18337

This is where it hangs and never finishes.  I have deleted the obj and bin folders too.
`.jar obj\Debug\net8.0-android\lp\541\jl\libs\7909489DBF6E3AD5.jar obj\Debug\net8.0-android\lp\542\jl\libs\7901EFB63BB8846B.jar obj\Debug\net8.0-android\lp\543\jl\libs\8E428AF64A795598.jar obj\Debug\net8.0-android\lp\65\jl\bin\classes.jar obj\Debug\net8.0-android\lp\78\jl\bin\classes.jar --map-diagnostics warning info `

**Comment by AdamDiament** [comment]
Hey @logikonline , did you update your Android only nuget dependencies as per the readme file? And does your app compile for android 14?

**Comment by logikonline** [comment]
I was using the nuget but I shifted to another package.  I appreciate the reply, though.
